name: Automated DEV Release

on:
  push:
    branches:
      - "main"
      - "release/**"

jobs:
  release-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build -x test
        env:
          RUN_NUMBER: ${{ github.run_number }}
      - name: Read version properties
        id: read_version_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: 'version.properties'
          properties: 'version shortVersion tag branch'
      - name: Delete previous tag and release
        uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: ${{ steps.read_version_properties.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dev',
              sha: context.sha
            })
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            build/distributions/**
          name: ${{ steps.read_version_properties.outputs.version }}
          tag_name: ${{ steps.read_version_properties.outputs.tag }}
          body_path: docs/md/release_notes.md
          target_commitish: ${{ steps.read_version_properties.outputs.branch }}
          draft: false
          prerelease: true
      - name: If not dev-release delete previous short version tag
        if: ${{ steps.read_version_properties.outputs.tag != 'dev'}}
        uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: ${{ steps.read_version_properties.outputs.shortVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: If not dev-release create a Release with short version tag
        if: ${{ steps.read_version_properties.outputs.tag != 'dev'}}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            build/distributions/**
          name: ${{ steps.read_version_properties.outputs.version }}
          tag_name: ${{ steps.read_version_properties.outputs.shortVersion }}
          body_path: docs/md/release_notes.md
          target_commitish: ${{ steps.read_version_properties.outputs.branch }}
          prerelease: ${{ steps.read_version_properties.outputs.tag != 'tag_stable'}}
