name: Automated DEV Release

on:
  push:
    branches:
      - "main"
      - "release/**"

jobs:
  release-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Build with Gradle
        run: ./gradlew build -x test
        env:
          RUN_NUMBER: ${{ github.run_number }}
      - name: Read version properties
        id: read_version_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: 'version.properties'
          properties: 'version shortVersion tag branch'
      - name: Delete previous tag and release
        uses: ClementTsang/delete-tag-and-release@v0.4.0
        with:
          delete_release: true
          tag_name: ${{ steps.read_version_properties.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/dev',
              sha: context.sha
            })
      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            build/distributions/**
          name: ${{ steps.read_version_properties.outputs.version }}
          tag_name: ${{ steps.read_version_properties.outputs.tag }}
          body_path: docs/md/release_notes.md
          target_commitish: ${{ steps.read_version_properties.outputs.branch }}
          draft: true
          prerelease: true
      - name: Publish Release
        uses: tychobrailleur/publish-action@0.1.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release: https://api.github.com/repos/tychobrailleur/kot-test/releases/${{ steps.create_release.outputs.id }}
      # - name: Publish Release
      #   run: |
      #     curl --request PATCH \
      #     --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'Content-type: application/json' \
      #     --header 'User-Agent: Github-Action' \
      #     --url https://api.github.com/repos/tychobrailleur/kot-test/releases/${{ steps.create_release.outputs.id }} \
      #     --data '{ "draft": false }'
      - name: If 'tag_stable' release, also create 'stable' tag
        if: ${{ steps.read_version_properties.outputs.tag == 'tag_stable' }}
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: stable
          tag_exists_error: false

          
