name: Automated DEV Release

on:
  push:
    branches:
      - "master"
      - "release/**"

jobs:
  release-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build -x test
        env:
          RUN_NUMBER: ${{ github.run_number }}